runtime: python312

env_variables:
  APPENGINE_URL: https://e-footprint-interface.nw.r.appspot.com

instance_class: F4
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.7
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: theme/static/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
